### ISSUE TITLE
Empty after logging in

### ISSUE THREAD

**Issue by Onnokh** [ceviixx/umami-Analytics-App#2]
**Describe the bug**
After signing in, you get an empty app without websites. You are unable to add a site, as it will say error when submitting. 

**To Reproduce**
1. Click selfhosted
2. Sign in with credentials

**Expected behavior**
A signed in view of the app. 

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ceviixx** [comment]
Hi @Onnokh, sorry for the delay. 

What version of umami you're using? Maybe there is an api change which I not handling. 
The newest version of umami works (checked at this moment). 

Which version of the app are you using?

**Comment by ceviixx** [comment]
@sambrucejoseph that's strange. 
The app v4.0.0 is tested with the host 2.13.2. 

When you login; does the login screen disappear and you see an empty dashboard, right?

**Comment by ceviixx** [comment]
Update is coming which includes logging, so we can check the response after login. 
If there an issue, you see it in the logs, and can share it.

**Comment by ceviixx** [comment]
The update is released.
Can you please check the logs?

Profile > Help and report issue > View logs

**Comment by sambrucejoseph** [comment]
@ceviixx  Thanks for publishing it so quickly.
It still shows No website when I already have some website in the account.

> When you login; does the login screen disappear and you see an empty dashboard, right?

Yes the login works fine. The dashboard says No websites ([Screenshot](https://github.com/user-attachments/assets/ce7d81d2-ee24-4bcb-8c1d-2d9858cdc745))


Here are the logs I'm seeing:

```
{"route":"\/api\/users\/41e2b680-648e-4b09-bcd7-3e2b10c06264\/teams","message":"","dataString":"401 Unauthorized","type":"No 2xx status code (401)"}

{"dataString":"401 Unauthorized","type":"No 2xx status code (401)","route":"\/api\/users\/41e2b680-648e-4b09-bcd7-3e2b10c06264\/websites","message":""}

{"type":"fatalError","route":"\/api\/users\/41e2b680-648e-4b09-bcd7-3e2b10c06264\/teams","message":"cancelled","dataString":""}

{"type":"fatalError","route":"\/api\/users\/41e2b680-648e-4b09-bcd7-3e2b10c06264\/websites","message":"cancelled","dataString":""}

{"dataString":"","message":"cancelled","route":"\/api\/users\/41e2b680-648e-4b09-bcd7-3e2b10c06264\/teams","type":"fatalError"}

{"type":"fatalError","route":"\/api\/users\/41e2b680-648e-4b09-bcd7-3e2b10c06264\/websites","message":"cancelled","dataString":""}

{"message":"","dataString":"401 Unauthorized","type":"No 2xx status code (401)","route":"\/api\/users\/41e2b680-648e-4b09-bcd7-3e2b10c06264\/teams"}

{"dataString":"401 Unauthorized","type":"No 2xx status code (401)","route":"\/api\/users\/41e2b680-648e-4b09-bcd7-3e2b10c06264\/websites","message":""}
```

**Comment by ceviixx** [comment]
@sambrucejoseph thanks for your feedback. 

The log says 401 unauthorized, can you please try to sign out (Profile) and then sign in again?

**Comment by Onnokh** [comment]
It still happens, it looks like it receives a 401/404 and still continues the login. 

After getting the cursed session, you kinda get an empty app, no sites, users. 

If it makes a difference, I am hosting on a subdomain. When I go there on a browser with the same credentials I can successfully login.

**Comment by ceviixx** [comment]
@Onnokh 401, did you logout and login again?

**Comment by Onnokh** [comment]
> @Onnokh 401 means that there is no permission, did you logout and login again?

Yes. Could it be related to self hosting it on a subdomain? E.g. https://analytics.website.com

**Comment by ceviixx** [comment]
> Yes. Could it be related to self hosting it on a subdomain? E.g. https://analytics.website.com

That's strange, subdomains should work - tested on domain like https://analytics.website.com

**Comment by Onnokh** [comment]
![image](https://github.com/user-attachments/assets/ce88464d-b982-483c-b095-19058abf884a)

After logging in, you get in a infinite loop now, which ddosses my instance with api calls. Here is a small batch

**Comment by Onnokh** [comment]
![image](https://github.com/user-attachments/assets/3dd89492-0c96-4c00-aac3-41e5abb68149)

**Comment by ceviixx** [comment]
@Onnokh okay now it's really strange. 
"No valid URL" means, that there is no hostname. 

I'll try to release an new version in an short time to the App Store - currently only on TestFlight

**Comment by ceviixx** [comment]
@Onnokh the problem is, I can not reproduce the problem

**Comment by Onnokh** [comment]
After getting the test flight version, it works! :)

**Comment by ceviixx** [comment]
Nice, thanks for your feedback! : )


Need to fix some issues on the new features and then the new version will released to the App Store.

**Comment by Onnokh** [comment]
Is this getting released soon?

**Comment by ceviixx** [comment]
Though your issue is solved? But the new release handles issues better and I hope I can submit end this week to Apple. If it's accepted, I'll release it as soon as possible.

**Comment by Onnokh** [comment]
I was using the TestFlight version. But in that one the Widgets broke, it always has an empty lists of projects. So I still cannot have the easy access on my homescreen.

**Comment by ceviixx** [comment]
The empty list on widgets is because of the login issue. 
This should be fix if the login (multiple hosts) work again. 

If you have some widget wishes, you can contact on discord or write your wish here.
